apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    # can be accessed only by pods on the same worker node
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
